GET http://localhost:8000/api/rooms/check-room/1/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjk2MzYzMDY2LCJpYXQiOjE2OTYyNzY2NjYsImp0aSI6ImQ4ZmU3NWExZGNmYjRmNGE4YTY2NDZhM2M3YTE3OWEzIiwidXNlcl9pZCI6MiwibmFtZSI6InJvb20xIiwicm9vbSI6eyJpZCI6MSwicm9vbV9uYW1lIjoiUm9vbSAjMSIsInVzZXIiOjJ9fQ.H3WnASyvxrhxQsiJWg94k7v9svZLutYak8vrBsnK0mk
