GET http://localhost:8000/api/rooms/2/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjk2MjQyMDYxLCJpYXQiOjE2OTYyNDE3NjEsImp0aSI6ImQ1ZDRkY2Y4ZmYzZDQ4MDQ5MGE2NTVlNmUxYTgwNDYzIiwidXNlcl9pZCI6MiwibmFtZSI6InJvb20xIiwiaXNfcm9vbSI6dHJ1ZX0.6do03MJYaNh2fCXXG8Yy6WUIbD1qT3gtPLBJlXdwEuE