from django.contrib import admin
from django.urls import path, include
from rest_framework import routers

router = routers.DefaultRouter()

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/rooms/', include('rooms.urls')),  # Include the 'rooms' URLs
]

urlpatterns += router.urls  # Include the URLs generated by DefaultRouter