import "./globals.css";
import type { Metadata } from "next";
import { Toaster } from "react-hot-toast";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <main className="flex justify-center items-center min-h-screen lg:h-screen bg-gray-100">
          <Toaster position="bottom-left" />
          {children}
        </main>
      </body>
    </html>
  );
}
