# Generated by Django 4.2.5 on 2023-09-26 08:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('occupied', models.BooleanField(verbose_name='occupied')),
            ],
            options={
                'verbose_name_plural': 'Rooms',
            },
        ),
    ]
