# Generated by Django 4.2.5 on 2023-09-26 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_name',
            field=models.CharField(default='Roomx', max_length=255, verbose_name='room_name'),
            preserve_default=False,
        ),
    ]
