# Generated by Django 4.2.5 on 2023-10-17 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomreservation',
            name='occupied',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
