# Generated by Django 4.2.5 on 2023-10-17 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_alter_roomreservation_occupied'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomreservation',
            old_name='occupied',
            new_name='reserved',
        ),
    ]
