# Generated by Django 4.2.5 on 2023-10-18 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_rename_reserved_roomreservation_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomreservation',
            old_name='active',
            new_name='ended_earlier',
        ),
    ]
