# Generated by Django 4.2.5 on 2023-10-18 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_rename_active_roomreservation_ended_earlier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomreservation',
            name='ended_earlier',
            field=models.BooleanField(default=False),
        ),
    ]
